SELECT USER_ID, NICKNAME, SUM(PRICE) AS 'TOTAL_SALES'
FROM USED_GOODS_USER u
JOIN USED_GOODS_BOARD b
    ON b.WRITER_ID = u.USER_ID
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY 3 ASC;