SELECT CATEGORY, SUM(SALES) AS 'TOTAL_SALES'
FROM BOOK b
JOIN BOOK_SALES s 
    ON b.BOOK_ID = s.BOOK_ID 
    AND SALES_DATE >= '2022-01-01' AND SALES_DATE <= '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY

